<?php
/**
 * @author Исаков Владислав <isakov.vi@dns-shop.ru>
 */

namespace common\modules\rbac\controllers;


use common\modules\rbac\rules\Permissions;
use yii\web\Controller;
use Yii;
use yii\web\ForbiddenHttpException;

class RbacController extends Controller {
	public function beforeAction($action) {
		if (!Yii::$app->user->can(Permissions::ROLE_ADMIN)) {
			throw new ForbiddenHttpException('Доступ запрещен');
		}

		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
}