<?php
/**
 * @author Исаков Владислав <visakov@biletur.ru>
 */

namespace common\components;

use common\components\tour\CommonTour;
use common\modules\seo\models\Seo;

class FrontendMenuController extends FrontendController {
	public function beforeAction($action) {
		$this->layout = 'common';

		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
}